### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#194]
I 2017_01 branch er der en ny runcontainer.sh den skal nok erstattes med en docker compose.

**Comment by JosefAssad** [comment]
Klaret, findes i dev og næste version bliver docker-composable.

**Comment by baffioso** [comment]
@JosefAssad Har lige prøvet at installere wiki på lokalt på min maskine. Her er min docker-composer.yml

```yml
version: '3'
services:
  semawi:
    build:
      context: .
      dockerfile: Dockerfile
    image: semawi:2017_01
    ports:
      - "80:80"
    volumes:
      - /Users/andersbarfod/Documents/semawi/SeMaWi/mutables/LocalSettings.php:/var/www/wiki/LocalSettings.php
      - /Users/andersbarfod/Documents/semawi/SeMaWi/mutables/php.ini:/etc/php5/apache2/php.ini
      - /Users/andersbarfod/Documents/semawi/SeMaWi/mutables/images/:/var/www/wiki/images/
      - /Users/andersbarfod/Documents/semawi/SeMaWi/mutables/nanlogo.png:/var/www/wiki/resources/assets/nanlogo.png
      - /Users/andersbarfod/Documents/semawi/SeMaWi/mutables/gc2smw.cfg:/opt/gc2/gc2smw.cfg
      - /Users/andersbarfod/Documents/semawi/SeMaWi/mutables/freetds.conf:/etc/freetds/freetds.conf
      - /Users/andersbarfod/Documents/semawi/SeMaWi/mutables/odbcinst.ini:/etc/odbcinst.ini
      - /Users/andersbarfod/Documents/semawi/SeMaWi/mutables/odbc.ini:/etc/odbc.ini
    networks:
      - wiki_network
    container_name: semawi-mediawiki
    restart: on-failure
    depends_on:
      - wikidb
    hostname: semawi-mediawiki
  wikidb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: wiki
    networks:
      - wiki_network
    container_name: semawi-mysql
    hostname: semawi-mysql
    restart: on-failure

networks:
  wiki_network:
    driver: bridge
```

Og har sat wgServer til localhost  i LocalSettings.php
```php
$wgServer = "http://127.0.0.1";
```

Jeg kan sagtens tilgå DB og kan også se apache startsiden i min browser på localhost:80, men wiki kommer ikke frem.
